name: "Build"

on:
  push:
    branches-ignore:
      - "deployment"
      - "root"

  pull_request:
  merge_group:

env:
  ALGOLIA_ARTIFACT: "algolia-indexes-KORDEX.zip"
  ARTIFACT: "webHelpKORDEX2.zip"
  DOCKER_VERSION: "232.10165.1"
  INSTANCE: "./kordex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JetBrains/writerside-github-action@v4

        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - uses: actions/upload-artifact@v3

        with:
          name: artifact
          path: artifacts/${{ env.ARTIFACT }}

          retention-days: 7

      - uses: actions/upload-artifact@v3

        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}

          retention-days: 7