name: "Build"

on:
  push:
    branches-ignore:
      - "deployment"
      - "root"

  pull_request:
  merge_group:

env:
  ALGOLIA_ARTIFACT: "algolia-indexes-KORDEX.zip"
  ARTIFACT: "webHelpKORDEX2-all.zip"
  INSTANCE: "Writerside/kordex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Calculate latest KordEx version
        run: kotlin .github/set-version.main.kts

      - uses: JetBrains/writerside-github-action@v4

        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}

      - uses: actions/upload-artifact@v3

        with:
          name: artifact
          path: artifacts/${{ env.ARTIFACT }}

          retention-days: 7

      - uses: actions/upload-artifact@v3

        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}

          retention-days: 7