name: "Build"

on:
  push:
    branches-ignore:
      - "deployment"
      - "root"

  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

# TODO: Figure out what to do here
#      - name: Set up Kotlin
#        uses: fwilhe2/setup-kotlin@main
#
#      - name: Calculate latest KordEx version
#        run: kotlin .github/set-version.main.kts

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

        with:
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4

        with:
          node-version-file: "package.json"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install Dependencies
        run: pnpm i

      - name: Build Site
        run: pnpm run build

# TODO: Cloudflare like the site repo
      - name: Upload Build Site
        uses: actions/upload-artifact@v4

        with:
          name: docs

          path: |
            build/

          retention-days: 7
