name: "Build & Deploy"

on:
  push:
    branches:
      - "root"

  workflow_dispatch:

env:
  ALGOLIA_ARTIFACT: "algolia-indexes-KORDEX.zip"
  ARTIFACT: "webHelpKORDEX2-all.zip"
  INSTANCE: "Writerside/kordex"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Calculate latest KordEx version
        run: kotlin .github/set-version.main.kts

      - uses: JetBrains/writerside-github-action@v4

        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}

      - name: Add CSS and script to zip
        run: |
          zip artifacts/${{ env.ARTIFACT }} style.css .github/update-css.main.kts

      - uses: actions/upload-artifact@v3

        with:
          name: docs

          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json

          retention-days: 7

      - uses: actions/upload-artifact@v3

        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}

          retention-days: 7
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1

        with:
          name: docs
          path: artifacts

      - uses: JetBrains/writerside-checker-action@v1

        with:
          instance: ${{ env.INSTANCE }}
  deploy:
    # Requires the build job results
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Switch branch, create Algolia directory

        run: |
          git checkout --orphan deployment
          mkdir algolia

      #     bash -O extglob -c "rm -rf !(.git)"

      - uses: actions/download-artifact@v3

        with:
          name: algolia-indexes

      - uses: actions/download-artifact@v3

        with:
          name: docs

      - uses: montudor/action-zip@v1

        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d docs

      - uses: montudor/action-zip@v1

        with:
          args: unzip -qq ${{ env.ALGOLIA_ARTIFACT }} -d algolia

      - name: Combine algolia JSON files

        run: "jq -s . algolia/*.json > algolia/index.json"

      - uses: wangchucheng/algolia-uploader@master

        with:
          app_id: "00TQKB9RBW"
          admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          index_name: "KordEx Docs"
          index_file_path: "algolia/index.json"

      - name: Copy files, commit and push

        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions-user@users.noreply.github.com"
          
          cp -r docs/* .
          
          sudo rm -rf docs algolia Writerside
          
          kotlin update-css.main.kts
          
          sudo rm -f update-css.main.kts style.css
          
          git add .
          git commit -am "Automatic deployment"
          git push --force origin deployment
